//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Inqwise.Skipad.Common {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DsCampaignsStatistics")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DsCampaignsStatistics : global::System.Data.DataSet {
        
        private CampaignsDataTable tableCampaigns;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DsCampaignsStatistics() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DsCampaignsStatistics(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Campaigns"] != null)) {
                    base.Tables.Add(new CampaignsDataTable(ds.Tables["Campaigns"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CampaignsDataTable Campaigns {
            get {
                return this.tableCampaigns;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DsCampaignsStatistics cln = ((DsCampaignsStatistics)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Campaigns"] != null)) {
                    base.Tables.Add(new CampaignsDataTable(ds.Tables["Campaigns"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableCampaigns = ((CampaignsDataTable)(base.Tables["Campaigns"]));
            if ((initTable == true)) {
                if ((this.tableCampaigns != null)) {
                    this.tableCampaigns.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DsCampaignsStatistics";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DsCampaignsStatistics.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCampaigns = new CampaignsDataTable();
            base.Tables.Add(this.tableCampaigns);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeCampaigns() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DsCampaignsStatistics ds = new DsCampaignsStatistics();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void CampaignsRowChangeEventHandler(object sender, CampaignsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CampaignsDataTable : global::System.Data.TypedTableBase<CampaignsRow> {
            
            private global::System.Data.DataColumn columnCampaignId;
            
            private global::System.Data.DataColumn columnCampaignName;
            
            private global::System.Data.DataColumn columnServed;
            
            private global::System.Data.DataColumn columnVideoClicks;
            
            private global::System.Data.DataColumn columnCtrVideo;
            
            private global::System.Data.DataColumn columnComplete;
            
            private global::System.Data.DataColumn columnFirstQuartile;
            
            private global::System.Data.DataColumn columnMidPoint;
            
            private global::System.Data.DataColumn columnThirdQuartile;
            
            private global::System.Data.DataColumn columnBounceRate;
            
            private global::System.Data.DataColumn columnMute;
            
            private global::System.Data.DataColumn columnPaused;
            
            private global::System.Data.DataColumn columnSlideStarted;
            
            private global::System.Data.DataColumn columnFittedImage;
            
            private global::System.Data.DataColumn columnPercentFitFromServed;
            
            private global::System.Data.DataColumn columnPercentSuccessFit;
            
            private global::System.Data.DataColumn columnSliderMissed;
            
            private global::System.Data.DataColumn columnSkipButton;
            
            private global::System.Data.DataColumn columnSkipSlider;
            
            private global::System.Data.DataColumn columnClickedImage;
            
            private global::System.Data.DataColumn columnCtrImage;
            
            private global::System.Data.DataColumn columnPercentSlideStartedFromServed;
            
            private global::System.Data.DataColumn columnAVGEngagementTime;
            
            private global::System.Data.DataColumn columnTotalEngagementTime;
            
            private global::System.Data.DataColumn columnShare;
            
            private global::System.Data.DataColumn columnReplay;
            
            private global::System.Data.DataColumn columnRateVoted;
            
            private global::System.Data.DataColumn columnAvgRate;
            
            private global::System.Data.DataColumn columnValidView;
            
            private global::System.Data.DataColumn columnCtrFromFit;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsDataTable() {
                this.TableName = "Campaigns";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal CampaignsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected CampaignsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CampaignIdColumn {
                get {
                    return this.columnCampaignId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CampaignNameColumn {
                get {
                    return this.columnCampaignName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ServedColumn {
                get {
                    return this.columnServed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn VideoClicksColumn {
                get {
                    return this.columnVideoClicks;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CtrVideoColumn {
                get {
                    return this.columnCtrVideo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CompleteColumn {
                get {
                    return this.columnComplete;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FirstQuartileColumn {
                get {
                    return this.columnFirstQuartile;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MidPointColumn {
                get {
                    return this.columnMidPoint;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ThirdQuartileColumn {
                get {
                    return this.columnThirdQuartile;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BounceRateColumn {
                get {
                    return this.columnBounceRate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MuteColumn {
                get {
                    return this.columnMute;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PausedColumn {
                get {
                    return this.columnPaused;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SlideStartedColumn {
                get {
                    return this.columnSlideStarted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FittedImageColumn {
                get {
                    return this.columnFittedImage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PercentFitFromServedColumn {
                get {
                    return this.columnPercentFitFromServed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PercentSuccessFitColumn {
                get {
                    return this.columnPercentSuccessFit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SliderMissedColumn {
                get {
                    return this.columnSliderMissed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SkipButtonColumn {
                get {
                    return this.columnSkipButton;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SkipSliderColumn {
                get {
                    return this.columnSkipSlider;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ClickedImageColumn {
                get {
                    return this.columnClickedImage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CtrImageColumn {
                get {
                    return this.columnCtrImage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PercentSlideStartedFromServedColumn {
                get {
                    return this.columnPercentSlideStartedFromServed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AVGEngagementTimeColumn {
                get {
                    return this.columnAVGEngagementTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TotalEngagementTimeColumn {
                get {
                    return this.columnTotalEngagementTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ShareColumn {
                get {
                    return this.columnShare;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ReplayColumn {
                get {
                    return this.columnReplay;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RateVotedColumn {
                get {
                    return this.columnRateVoted;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn AvgRateColumn {
                get {
                    return this.columnAvgRate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ValidViewColumn {
                get {
                    return this.columnValidView;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CtrFromFitColumn {
                get {
                    return this.columnCtrFromFit;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsRow this[int index] {
                get {
                    return ((CampaignsRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CampaignsRowChangeEventHandler CampaignsRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CampaignsRowChangeEventHandler CampaignsRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CampaignsRowChangeEventHandler CampaignsRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CampaignsRowChangeEventHandler CampaignsRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddCampaignsRow(CampaignsRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsRow AddCampaignsRow(
                        int CampaignId, 
                        string CampaignName, 
                        int Served, 
                        int VideoClicks, 
                        double CtrVideo, 
                        int Complete, 
                        int FirstQuartile, 
                        int MidPoint, 
                        int ThirdQuartile, 
                        double BounceRate, 
                        int Mute, 
                        int Paused, 
                        int SlideStarted, 
                        int FittedImage, 
                        double PercentFitFromServed, 
                        double PercentSuccessFit, 
                        int SliderMissed, 
                        int SkipButton, 
                        int SkipSlider, 
                        int ClickedImage, 
                        double CtrImage, 
                        double PercentSlideStartedFromServed, 
                        double AVGEngagementTime, 
                        long TotalEngagementTime, 
                        int Share, 
                        int Replay, 
                        int RateVoted, 
                        decimal AvgRate, 
                        int ValidView, 
                        double CtrFromFit) {
                CampaignsRow rowCampaignsRow = ((CampaignsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CampaignId,
                        CampaignName,
                        Served,
                        VideoClicks,
                        CtrVideo,
                        Complete,
                        FirstQuartile,
                        MidPoint,
                        ThirdQuartile,
                        BounceRate,
                        Mute,
                        Paused,
                        SlideStarted,
                        FittedImage,
                        PercentFitFromServed,
                        PercentSuccessFit,
                        SliderMissed,
                        SkipButton,
                        SkipSlider,
                        ClickedImage,
                        CtrImage,
                        PercentSlideStartedFromServed,
                        AVGEngagementTime,
                        TotalEngagementTime,
                        Share,
                        Replay,
                        RateVoted,
                        AvgRate,
                        ValidView,
                        CtrFromFit};
                rowCampaignsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowCampaignsRow);
                return rowCampaignsRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                CampaignsDataTable cln = ((CampaignsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CampaignsDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCampaignId = base.Columns["CampaignId"];
                this.columnCampaignName = base.Columns["CampaignName"];
                this.columnServed = base.Columns["Served"];
                this.columnVideoClicks = base.Columns["VideoClicks"];
                this.columnCtrVideo = base.Columns["CtrVideo"];
                this.columnComplete = base.Columns["Complete"];
                this.columnFirstQuartile = base.Columns["FirstQuartile"];
                this.columnMidPoint = base.Columns["MidPoint"];
                this.columnThirdQuartile = base.Columns["ThirdQuartile"];
                this.columnBounceRate = base.Columns["BounceRate"];
                this.columnMute = base.Columns["Mute"];
                this.columnPaused = base.Columns["Paused"];
                this.columnSlideStarted = base.Columns["SlideStarted"];
                this.columnFittedImage = base.Columns["FittedImage"];
                this.columnPercentFitFromServed = base.Columns["PercentFitFromServed"];
                this.columnPercentSuccessFit = base.Columns["PercentSuccessFit"];
                this.columnSliderMissed = base.Columns["SliderMissed"];
                this.columnSkipButton = base.Columns["SkipButton"];
                this.columnSkipSlider = base.Columns["SkipSlider"];
                this.columnClickedImage = base.Columns["ClickedImage"];
                this.columnCtrImage = base.Columns["CtrImage"];
                this.columnPercentSlideStartedFromServed = base.Columns["PercentSlideStartedFromServed"];
                this.columnAVGEngagementTime = base.Columns["AVGEngagementTime"];
                this.columnTotalEngagementTime = base.Columns["TotalEngagementTime"];
                this.columnShare = base.Columns["Share"];
                this.columnReplay = base.Columns["Replay"];
                this.columnRateVoted = base.Columns["RateVoted"];
                this.columnAvgRate = base.Columns["AvgRate"];
                this.columnValidView = base.Columns["ValidView"];
                this.columnCtrFromFit = base.Columns["CtrFromFit"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCampaignId = new global::System.Data.DataColumn("CampaignId", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaignId);
                this.columnCampaignName = new global::System.Data.DataColumn("CampaignName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaignName);
                this.columnServed = new global::System.Data.DataColumn("Served", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnServed);
                this.columnVideoClicks = new global::System.Data.DataColumn("VideoClicks", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVideoClicks);
                this.columnCtrVideo = new global::System.Data.DataColumn("CtrVideo", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCtrVideo);
                this.columnComplete = new global::System.Data.DataColumn("Complete", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnComplete);
                this.columnFirstQuartile = new global::System.Data.DataColumn("FirstQuartile", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFirstQuartile);
                this.columnMidPoint = new global::System.Data.DataColumn("MidPoint", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMidPoint);
                this.columnThirdQuartile = new global::System.Data.DataColumn("ThirdQuartile", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThirdQuartile);
                this.columnBounceRate = new global::System.Data.DataColumn("BounceRate", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBounceRate);
                this.columnMute = new global::System.Data.DataColumn("Mute", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMute);
                this.columnPaused = new global::System.Data.DataColumn("Paused", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPaused);
                this.columnSlideStarted = new global::System.Data.DataColumn("SlideStarted", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSlideStarted);
                this.columnFittedImage = new global::System.Data.DataColumn("FittedImage", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFittedImage);
                this.columnPercentFitFromServed = new global::System.Data.DataColumn("PercentFitFromServed", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPercentFitFromServed);
                this.columnPercentSuccessFit = new global::System.Data.DataColumn("PercentSuccessFit", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPercentSuccessFit);
                this.columnSliderMissed = new global::System.Data.DataColumn("SliderMissed", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSliderMissed);
                this.columnSkipButton = new global::System.Data.DataColumn("SkipButton", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSkipButton);
                this.columnSkipSlider = new global::System.Data.DataColumn("SkipSlider", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSkipSlider);
                this.columnClickedImage = new global::System.Data.DataColumn("ClickedImage", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnClickedImage);
                this.columnCtrImage = new global::System.Data.DataColumn("CtrImage", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCtrImage);
                this.columnPercentSlideStartedFromServed = new global::System.Data.DataColumn("PercentSlideStartedFromServed", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPercentSlideStartedFromServed);
                this.columnAVGEngagementTime = new global::System.Data.DataColumn("AVGEngagementTime", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAVGEngagementTime);
                this.columnTotalEngagementTime = new global::System.Data.DataColumn("TotalEngagementTime", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotalEngagementTime);
                this.columnShare = new global::System.Data.DataColumn("Share", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnShare);
                this.columnReplay = new global::System.Data.DataColumn("Replay", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReplay);
                this.columnRateVoted = new global::System.Data.DataColumn("RateVoted", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRateVoted);
                this.columnAvgRate = new global::System.Data.DataColumn("AvgRate", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAvgRate);
                this.columnValidView = new global::System.Data.DataColumn("ValidView", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnValidView);
                this.columnCtrFromFit = new global::System.Data.DataColumn("CtrFromFit", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCtrFromFit);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCampaignId}, false));
                this.columnCampaignId.AllowDBNull = false;
                this.columnCampaignId.ReadOnly = true;
                this.columnCampaignId.Unique = true;
                this.columnCampaignName.AllowDBNull = false;
                this.columnCampaignName.ReadOnly = true;
                this.columnServed.ReadOnly = true;
                this.columnVideoClicks.ReadOnly = true;
                this.columnCtrVideo.ReadOnly = true;
                this.columnCtrVideo.DefaultValue = ((double)(0D));
                this.columnComplete.ReadOnly = true;
                this.columnFirstQuartile.ReadOnly = true;
                this.columnMidPoint.ReadOnly = true;
                this.columnThirdQuartile.ReadOnly = true;
                this.columnBounceRate.ReadOnly = true;
                this.columnMute.ReadOnly = true;
                this.columnPaused.ReadOnly = true;
                this.columnSlideStarted.ReadOnly = true;
                this.columnFittedImage.ReadOnly = true;
                this.columnPercentFitFromServed.ReadOnly = true;
                this.columnPercentFitFromServed.DefaultValue = ((double)(0D));
                this.columnPercentSuccessFit.ReadOnly = true;
                this.columnPercentSuccessFit.DefaultValue = ((double)(0D));
                this.columnSliderMissed.ReadOnly = true;
                this.columnSkipButton.ReadOnly = true;
                this.columnSkipSlider.ReadOnly = true;
                this.columnClickedImage.ReadOnly = true;
                this.columnCtrImage.ReadOnly = true;
                this.columnCtrImage.DefaultValue = ((double)(0D));
                this.columnPercentSlideStartedFromServed.DefaultValue = ((double)(0D));
                this.columnAVGEngagementTime.ReadOnly = true;
                this.columnAVGEngagementTime.DefaultValue = ((double)(0D));
                this.columnTotalEngagementTime.ReadOnly = true;
                this.columnTotalEngagementTime.DefaultValue = ((long)(0));
                this.columnShare.ReadOnly = true;
                this.columnReplay.ReadOnly = true;
                this.columnAvgRate.ReadOnly = true;
                this.columnValidView.ReadOnly = true;
                this.columnCtrFromFit.DefaultValue = ((double)(0D));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsRow NewCampaignsRow() {
                return ((CampaignsRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CampaignsRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(CampaignsRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CampaignsRowChanged != null)) {
                    this.CampaignsRowChanged(this, new CampaignsRowChangeEvent(((CampaignsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CampaignsRowChanging != null)) {
                    this.CampaignsRowChanging(this, new CampaignsRowChangeEvent(((CampaignsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CampaignsRowDeleted != null)) {
                    this.CampaignsRowDeleted(this, new CampaignsRowChangeEvent(((CampaignsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CampaignsRowDeleting != null)) {
                    this.CampaignsRowDeleting(this, new CampaignsRowChangeEvent(((CampaignsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveCampaignsRow(CampaignsRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DsCampaignsStatistics ds = new DsCampaignsStatistics();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CampaignsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class CampaignsRow : global::System.Data.DataRow {
            
            private CampaignsDataTable tableCampaigns;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal CampaignsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCampaigns = ((CampaignsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int CampaignId {
                get {
                    return ((int)(this[this.tableCampaigns.CampaignIdColumn]));
                }
                set {
                    this[this.tableCampaigns.CampaignIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CampaignName {
                get {
                    return ((string)(this[this.tableCampaigns.CampaignNameColumn]));
                }
                set {
                    this[this.tableCampaigns.CampaignNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Served {
                get {
                    if (this.IsServedNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ServedColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ServedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int VideoClicks {
                get {
                    if (this.IsVideoClicksNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.VideoClicksColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.VideoClicksColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double CtrVideo {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.CtrVideoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CtrVideo\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.CtrVideoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Complete {
                get {
                    if (this.IsCompleteNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.CompleteColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.CompleteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int FirstQuartile {
                get {
                    if (this.IsFirstQuartileNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.FirstQuartileColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.FirstQuartileColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int MidPoint {
                get {
                    if (this.IsMidPointNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.MidPointColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.MidPointColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ThirdQuartile {
                get {
                    if (this.IsThirdQuartileNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ThirdQuartileColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ThirdQuartileColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double BounceRate {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.BounceRateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BounceRate\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.BounceRateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Mute {
                get {
                    if (this.IsMuteNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.MuteColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.MuteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Paused {
                get {
                    if (this.IsPausedNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.PausedColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.PausedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int SlideStarted {
                get {
                    if (this.IsSlideStartedNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.SlideStartedColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.SlideStartedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int FittedImage {
                get {
                    if (this.IsFittedImageNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.FittedImageColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.FittedImageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double PercentFitFromServed {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.PercentFitFromServedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PercentFitFromServed\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.PercentFitFromServedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double PercentSuccessFit {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.PercentSuccessFitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PercentSuccessFit\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.PercentSuccessFitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int SliderMissed {
                get {
                    if (this.IsSliderMissedNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.SliderMissedColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.SliderMissedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int SkipButton {
                get {
                    if (this.IsSkipButtonNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.SkipButtonColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.SkipButtonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int SkipSlider {
                get {
                    if (this.IsSkipSliderNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.SkipSliderColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.SkipSliderColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ClickedImage {
                get {
                    if (this.IsClickedImageNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ClickedImageColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ClickedImageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double CtrImage {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.CtrImageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CtrImage\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.CtrImageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double PercentSlideStartedFromServed {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.PercentSlideStartedFromServedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PercentSlideStartedFromServed\' in table \'Campaigns\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.PercentSlideStartedFromServedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double AVGEngagementTime {
                get {
                    if (this.IsAVGEngagementTimeNull()) {
                        return 0D;
                    }
                    else {
                        return ((double)(this[this.tableCampaigns.AVGEngagementTimeColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.AVGEngagementTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public long TotalEngagementTime {
                get {
                    if (this.IsTotalEngagementTimeNull()) {
                        return 0;
                    }
                    else {
                        return ((long)(this[this.tableCampaigns.TotalEngagementTimeColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.TotalEngagementTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Share {
                get {
                    if (this.IsShareNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ShareColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ShareColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Replay {
                get {
                    if (this.IsReplayNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ReplayColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ReplayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int RateVoted {
                get {
                    if (this.IsRateVotedNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.RateVotedColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.RateVotedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal AvgRate {
                get {
                    if (this.IsAvgRateNull()) {
                        return 0.0m;
                    }
                    else {
                        return ((decimal)(this[this.tableCampaigns.AvgRateColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.AvgRateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ValidView {
                get {
                    if (this.IsValidViewNull()) {
                        return 0;
                    }
                    else {
                        return ((int)(this[this.tableCampaigns.ValidViewColumn]));
                    }
                }
                set {
                    this[this.tableCampaigns.ValidViewColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double CtrFromFit {
                get {
                    try {
                        return ((double)(this[this.tableCampaigns.CtrFromFitColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CtrFromFit\' in table \'Campaigns\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCampaigns.CtrFromFitColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsServedNull() {
                return this.IsNull(this.tableCampaigns.ServedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetServedNull() {
                this[this.tableCampaigns.ServedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsVideoClicksNull() {
                return this.IsNull(this.tableCampaigns.VideoClicksColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetVideoClicksNull() {
                this[this.tableCampaigns.VideoClicksColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCtrVideoNull() {
                return this.IsNull(this.tableCampaigns.CtrVideoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCtrVideoNull() {
                this[this.tableCampaigns.CtrVideoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCompleteNull() {
                return this.IsNull(this.tableCampaigns.CompleteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCompleteNull() {
                this[this.tableCampaigns.CompleteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFirstQuartileNull() {
                return this.IsNull(this.tableCampaigns.FirstQuartileColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFirstQuartileNull() {
                this[this.tableCampaigns.FirstQuartileColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMidPointNull() {
                return this.IsNull(this.tableCampaigns.MidPointColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMidPointNull() {
                this[this.tableCampaigns.MidPointColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsThirdQuartileNull() {
                return this.IsNull(this.tableCampaigns.ThirdQuartileColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetThirdQuartileNull() {
                this[this.tableCampaigns.ThirdQuartileColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBounceRateNull() {
                return this.IsNull(this.tableCampaigns.BounceRateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBounceRateNull() {
                this[this.tableCampaigns.BounceRateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMuteNull() {
                return this.IsNull(this.tableCampaigns.MuteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMuteNull() {
                this[this.tableCampaigns.MuteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPausedNull() {
                return this.IsNull(this.tableCampaigns.PausedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPausedNull() {
                this[this.tableCampaigns.PausedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSlideStartedNull() {
                return this.IsNull(this.tableCampaigns.SlideStartedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSlideStartedNull() {
                this[this.tableCampaigns.SlideStartedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFittedImageNull() {
                return this.IsNull(this.tableCampaigns.FittedImageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFittedImageNull() {
                this[this.tableCampaigns.FittedImageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPercentFitFromServedNull() {
                return this.IsNull(this.tableCampaigns.PercentFitFromServedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPercentFitFromServedNull() {
                this[this.tableCampaigns.PercentFitFromServedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPercentSuccessFitNull() {
                return this.IsNull(this.tableCampaigns.PercentSuccessFitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPercentSuccessFitNull() {
                this[this.tableCampaigns.PercentSuccessFitColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSliderMissedNull() {
                return this.IsNull(this.tableCampaigns.SliderMissedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSliderMissedNull() {
                this[this.tableCampaigns.SliderMissedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSkipButtonNull() {
                return this.IsNull(this.tableCampaigns.SkipButtonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSkipButtonNull() {
                this[this.tableCampaigns.SkipButtonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSkipSliderNull() {
                return this.IsNull(this.tableCampaigns.SkipSliderColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSkipSliderNull() {
                this[this.tableCampaigns.SkipSliderColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsClickedImageNull() {
                return this.IsNull(this.tableCampaigns.ClickedImageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetClickedImageNull() {
                this[this.tableCampaigns.ClickedImageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCtrImageNull() {
                return this.IsNull(this.tableCampaigns.CtrImageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCtrImageNull() {
                this[this.tableCampaigns.CtrImageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPercentSlideStartedFromServedNull() {
                return this.IsNull(this.tableCampaigns.PercentSlideStartedFromServedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPercentSlideStartedFromServedNull() {
                this[this.tableCampaigns.PercentSlideStartedFromServedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAVGEngagementTimeNull() {
                return this.IsNull(this.tableCampaigns.AVGEngagementTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAVGEngagementTimeNull() {
                this[this.tableCampaigns.AVGEngagementTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTotalEngagementTimeNull() {
                return this.IsNull(this.tableCampaigns.TotalEngagementTimeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTotalEngagementTimeNull() {
                this[this.tableCampaigns.TotalEngagementTimeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsShareNull() {
                return this.IsNull(this.tableCampaigns.ShareColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetShareNull() {
                this[this.tableCampaigns.ShareColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReplayNull() {
                return this.IsNull(this.tableCampaigns.ReplayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReplayNull() {
                this[this.tableCampaigns.ReplayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRateVotedNull() {
                return this.IsNull(this.tableCampaigns.RateVotedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRateVotedNull() {
                this[this.tableCampaigns.RateVotedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAvgRateNull() {
                return this.IsNull(this.tableCampaigns.AvgRateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAvgRateNull() {
                this[this.tableCampaigns.AvgRateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsValidViewNull() {
                return this.IsNull(this.tableCampaigns.ValidViewColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetValidViewNull() {
                this[this.tableCampaigns.ValidViewColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCtrFromFitNull() {
                return this.IsNull(this.tableCampaigns.CtrFromFitColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCtrFromFitNull() {
                this[this.tableCampaigns.CtrFromFitColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class CampaignsRowChangeEvent : global::System.EventArgs {
            
            private CampaignsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsRowChangeEvent(CampaignsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CampaignsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591